const nameMap = {
  "核价需求录入界面": { classify: "核价需求", title: "需求录入" },
  "项目经理录入界面": { classify: "核价需求", title: "核价工作分配" },
  "市场部TR主方案审核界面": { classify: "核价需求", title: "TR方案审核" },
  "产品开发部TR主方案审核": { classify: "核价需求", title: "TR方案审核" },
  "电子bom导入界面": { classify: "BOM核价", title: "电子bom" },
  "电子bom审核界面": { classify: "BOM核价", title: "电子bom审核" },
  "结构bom导入界面": { classify: "BOM核价", title: "结构bom" },
  "结构bom审核界面": { classify: "BOM核价", title: "结构bom审核" },
  "电子单价录入界面": { classify: "BOM核价", title: "电子单价" },
  "电子bom单价审核界面": { classify: "BOM核价", title: "电子单价审核" },
  "结构单价录入界面": { classify: "BOM核价", title: "结构单价" },
  "结构bom单价审核界面": { classify: "BOM核价", title: "结构单价审核" },
  "工序工时导入界面": { classify: "BOM核价", title: "制造费用" },
  "工程电子损耗率录入界面": { classify: "BOM核价", title: "电子损耗" },
  "工程结构损耗率录入界面": { classify: "BOM核价", title: "结构损耗" },
  "物流成本录入界面": { classify: "BOM核价", title: "物流费用" },
  "制造成本录入界面": { classify: "BOM核价", title: "SMT/COB制造费用" },
  "NRE模具清单录入界面": { classify: "NRE核价", title: "模具费用" },
  "NRE检具费用录入界面": { classify: "NRE核价", title: "检具费用" },
  "NRE核价电子-EMC实验费录入界面": { classify: "NRE核价", title: "EMC实验费" },
  "NRE实验费用录入界面": { classify: "NRE核价", title: "可靠性实验费" },
  "NRE核价手板件、差旅及其他费用录入界面": { classify: "NRE核价", title: "手板件/其他费用" },
  "工序工时导入界面2": { classify: "NRE核价", title: "治具/工装/设备/软件费用" },
  "贸易合规审核（结束流程&退回流程）": { classify: "核价审核", title: "贸易合规判定" },
  "核价看板&流程退回界面": { classify: "核价审核", title: "核价看板" },
  "项目部核价审核界面": { classify: "核价审核", title: "核价看板" },
  "财务部核价审核界面": { classify: "核价审核", title: "核价看板" },
  "成本信息表下载&填报NRE报价系数&产品报价看板界面": { classify: "报价审核", title: "报价分析" },
  "总经理报价审批界面": { classify: "报价审核", title: "总经理审核" },
  "报价单": { classify: "报价输出", title: "营销报价" },
  "报价回传单": { classify: "报价归档", title: "报价回传" },
  "归档下载界面": { classify: "报价归档", title: "归档（项目部）" },
}
export default nameMap
